name: Update Contributors

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  permissions:
    contents: write


jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Run contributor update script
        run: node scripts/update_contributors.js

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update contributors [skip ci]"
          git push